Agoric/ERTP

core/contractHost.js
core/issuers.js
core/mintController.js
demo/contractHost/bootstrap.js
demo/contractHost/vat-alice.js
demo/contractHost/vat-fred.js
demo/gallery/README.md
demo/gallery/bootstrap.js
demo/gallery/vat-alice.js
demo/gallery/vat-bob.js
demo/gallery/vat-mint.js
demo/pixel-demo/bootstrap.js
demo/pixel-demo/vat-alice.js
demo/pixel-demo/vat-mint.js
more/pixels/gallery.js
more/pixels/lruQueue.js
more/pixels/pixelAssays.js
more/pixels/pixelListAssay.js
more/pixels/pixelMintController.js
more/pixels/types/pixel.js
more/pixels/types/pixelList.js
test/demo/test-demos.js
test/demo/test-gallery-demo.js
test/more/pixels/test-gallery.js

This PR adds the following pixel demo functionality:
* The ability to revoke rights (held by a new abstraction, a `mintController`, which also controls the rights WeakMap in general)
* The ability to split an assay into use and transfer rights that are of themselves, full ERTP erights, and merge them back again
* XferRights and useRights aren't hardcoded into makeMint. Instead, there is only one rights WeakMap. All previous ERTP tests pass with this change, meaning that useRights was not being used yet in our tests. In this PR, the base right (a pixelList) is actually a compound right that can be split up by the Gallery upon request into use and transfer rights. Both are full erights themselves, so they act in all the usual ways, but they can also be merged back to together: upon receipt …

Gallery demo

---

more/pixels/gallery.js
test/demo/test-gallery-demo.js

This PR builds on #24 to fix all instances when the random colour needs to be six hex digits by left-padding shorter values with zeros.

gallery: generalise color-bleed fix with padStart

---

demo/contractHost/bootstrap.js
package-lock.json
package.json
test/demo/test-demos.js

This PR removes the last vestiges of the agoric-evaluate tarball.
In this case, the package-lock.json changes are desirable.

@agoric/swingset-vat: upgrade to 0.0.16

---

package.json

I couldn't find any reason why ERTP should depend on swingset for purposes other than testing.
However, I wan't able to run `npm test` either before or after this change for dependency problems that seem unrelated:
```
$ npm test
> @agoric/ertp@0.0.9-dev.1 test /Users/markmiller/src/ongithub/agoric/ERTP
> tape -r esm 'test/**/test*.js' | tap-spec
/Users/markmiller/src/ongithub/agoric/ERTP/node_modules/@agoric/swingset-vat/src/controller.js:1
Error: Cannot find module './kvstore'
Require stack:
- /Users/markmiller/src/ongithub/agoric/ERTP/node_modules/@agoric/swingset-vat/src/controller.js
- /Users/markmiller/src/ongithub/agoric/ERTP/node_modules/@agoric/swingset-vat/src/index.js
- /Users/markmiller/src/ongithub/agoric/ERTP/node_modules/@agoric/swingset-vat/src/main.js
- …
```

swingset should only be a dev dependency

---

core/contractHost.js
core/coveredCall.js
core/escrow.js
core/issuers.js
demo/contractHost/bootstrap.js
demo/contractHost/vat-alice.js
demo/contractHost/vat-bob.js
demo/contractHost/vat-fred.js
demo/gallery/vat-alice.js
demo/pixel-demo/bootstrap.js
demo/pixel-demo/vat-alice.js
demo/pixel-demo/vat-bob.js
more/pixels/gallery.js
package-lock.json
test/core/bootstrap.js
test/core/test-escrow.js
test/core/vat-host.js
test/core/vat-mint.js
test/demo/test-demos.js

refactor contractHost to simplify verification of invites.  …
Also add a helper for building amounts.
I wonder whether there's a way to move the added complexity of defining
contracts into the contractHost.
const escrowExchangeThunk = () =>
harden({
start(terms, inviteMaker) {
vs.
function escrowExchange(terms, inviteMaker) {

Refactor verification

---

more/pixels/gallery.js
test/swingsetTests/gallery/bootstrap.js
test/swingsetTests/gallery/vat-alice.js

This PR makes the gallery rely on a long-lived contract host in vat-host.js rather than calling `makeContractHost`. 
In making this change, I noticed that it might be a good idea to extract the functionality for creating the starting objects for tests, so I did that. Otherwise, it was too easy to accidentally change things in one line and not another. 
By moving `createSaleOffer` to be inside the `make` function for Alice, I was able to refactor it down to only two parameters.  
Closes #45

remove calls to makeContractHost outside of long-lived host vat

---

core/assays.chainmail
core/contractHost.chainmail

The IDL doesn't allow structs to declare that they extend another. I'll have to see if it makes sense to add that. For now, we'll comment out the declarations.

Repair chainmail Files

---

core/assays.chainmail
core/config/assays.js
more/pixels/pixelAssays.js

Closes #74 
In implementing #63, it became apparent that it would be helpful to be able to compare two amounts to see if they are equal. Specifically, we often use a pattern where an amount equal to the full balance is passed into `deposit`, `burn`, and `getExclusive` in order to check that our understanding of the balance is correct. Chris suggested changing `deposit`, `burn`, and `getExclusive` to `depositExactly`, `burnExactly`, and `getExclusiveExactly` to be able to still use this pattern even with payment linearity. 
The implementations of `depositExactly`, `burnExactly`, and `getExclusiveExactly` could use `equals` to easily compare the passed-in amount to the balance of the payment to fail-fast if the amount doesn't equal the balance. 
We can use `includes` in both directions as a …

Add 'equals' to assay

---

GALLERY-README.md
README.md

Change 'here' in links to more descriptive text for accessibility and SEO
Closes #90

Change 'here' in links to more descriptive text 

---

core/config/noCustomization.js
core/issuers.js
more/pixels/pixelConfig.js

Closes #79 
This PR changes the `makeMint` config to be more trait-like. Instead of the config being able to create an entirely custom payment/purse/etc, the config functions are only able to add additional methods to payments/purses/etc. We are able to enforce this securely by moving back to an "object merge" pattern in which a new object is created by using the spread operator (...) on both the "core" and "custom" method objects. We ensure that the object with the "core" methods is the second spread expression in the object merge, thus overwriting any custom methods in the same name space as the core methods.

Make the `makeMint` config more trait-like

---

more/imports/importManager.js
test/unitTests/more/imports/badImports.js
test/unitTests/more/imports/goodImports.js
test/unitTests/more/imports/strategy.js
test/unitTests/more/imports/test-importsA.js

As described in https://github.com/Agoric/ERTP/issues/102, it would be useful to allow modules to provide code for their clients to run locally without requiring round trips to the hosting objects. Zoe/Scooter might benefit from being able to execute code provided by strategies without needing to call methods in separate vats. Similarly, some of the verification code provided by contracts in the contract host could be run locally by a client.
This is an interim solution that works by directly importing the code into the client, but allowing the remote objects to dispatch to different polymorphic functions by returning a string to use as a selector.

Import manager

---

core/issuers.chainmail

A missing semicolon, and a missing type declaration.
In case this hasn't been documented previously, you can run chainmail with
```
git clone -b chainmail https://github.com/Agoric/jessica
npm install
jessica/lang/nodejs/cmparse.bat [single .chainmail file]
```

Chainmail typos

---

core/contractHost.js
core/zoe/zoe/zoe.js

This is also added to the contractHost, so that SwingSet users
can endow a `require` function for bundled contract code in the
`getExport` module format.

feat(zoe): allow specifying additional endowments for contracts

---

core/zoe/contracts/coveredCall.js
core/zoe/contracts/publicAuction.js
core/zoe/contracts/publicSwap.js
core/zoe/zoe/state.js
core/zoe/zoe/zoe.js
core/zoe/zoe/zoeUtils.js
test/swingsetTests/zoe/test-zoe.js
test/swingsetTests/zoe/vat-alice.js
test/swingsetTests/zoe/vat-bob.js
test/swingsetTests/zoe/vat-carol.js
test/swingsetTests/zoe/vat-dave.js
test/unitTests/core/zoe/contracts/test-automaticRefund.js
test/unitTests/core/zoe/contracts/test-coveredCall.js
test/unitTests/core/zoe/contracts/test-publicAuction.js
test/unitTests/core/zoe/contracts/test-publicSwap.js
test/unitTests/core/zoe/contracts/test-simpleExchange.js

Most of the time, users will use the exit condition "onDemand", which will allow them to cancel at will. This PR changes the exit condition used by default in tests to match this, rather than the previous choice, "noExit". 
This PR adds more tests and also alters most of the governing contracts to better check for exit. A few more still need to be done.

Change default exit condition in Zoe contract tests to "onDemand"

---

core/config/extentOps/uniExtentOps.js
core/zoe/zoe/zoe.js
test/unitTests/core/zoe/contracts/test-coveredCall.js

This PR adds two tests of higher order contract use. In both tests, an invite for a covered call is the underlying right of another contract. In one case, the other contract is a public swap. In the second, it's another copy of the same coveredCall.

Add tests for higher order contracts

---

.eslintignore
.gitignore
core/zoe/contracts/automaticRefund.js
core/zoe/contracts/autoswap.js
core/zoe/contracts/coveredCall.js
core/zoe/contracts/publicAuction.js
core/zoe/contracts/publicSwap.js
core/zoe/contracts/simpleExchange.js
package-lock.json
package.json
test/swingsetTests/zoe/bootstrap.js
test/swingsetTests/zoe/test-zoe.js
test/swingsetTests/zoe/vat-zoe.js
test/unitTests/core/zoe/contracts/test-automaticRefund.js
test/unitTests/core/zoe/contracts/test-autoswap.js
test/unitTests/core/zoe/contracts/test-coveredCall.js
test/unitTests/core/zoe/contracts/test-publicAuction.js
test/unitTests/core/zoe/contracts/test-publicSwap.js
test/unitTests/core/zoe/contracts/test-simpleExchange.js

Makes the Zoe contracts compatible with how we are using rollup to bundle files. This gives us the ability to split up a governing contract into separate files and to reuse components between files. 
This PR also changes the Zoe unit tests and SwingSet tests to use the bundler.
@michaelfig I used [your example PR](https://github.com/Agoric/ERTP/pull/176) heavily. Let me know if you want any changes.

Change Zoe Contracts to be compatible with "@agoric/bundle-source"

---

more/registrar/registrar.js
test/unitTests/more/registrar/test-registrar.js
util/sparseInts.js

~~PR FOR DISCUSSION ONLY~~
This illustrates the registrar naming service. You register an object with a key prefix, and it returns the key, of the form `<prefix>_<digits>`. The `digits` are from an integer in a sparse distribution. the distribution is deterministic, but this helps protect against typos resulting in generating another valid key.
```
command[0] home.registrar~.register('handoff', home.handoffService)
history[0] "handoff_4409"
command[1] home.registrar~.get('handoff')
history[1] Promise.reject("Error: Key must end with _<digits> (a string)\nSee console for error data.")
command[2] home.registrar~.get('handoff_4409')
history[2] [Presence o-51]
command[3] history[2] === home.handoffService
history[3] true
```
Outstanding issues:
- ~~no tests~~
- no iteration (may not be …

Registrar service

---

core/zoe/zoe/state.js
core/zoe/zoe/zoe.js
core/zoe/zoe/zoeUtils.js
test/swingsetTests/zoe/test-zoe.js
test/swingsetTests/zoe/vat-alice.js
test/swingsetTests/zoe/vat-carol.js
test/unitTests/core/zoe/contracts/test-automaticRefund.js
test/unitTests/core/zoe/contracts/test-publicSwap.js

This removes the ability to create an ERTP payment for the payout. The original motivation was to be able to transfer the rights to the payout, but let's push this to a later version so that the current version is easier to explain and analyze.

Remove payout payment.

---

core/config/seatConfig.js
core/seatMint.js
core/zoe/contracts/autoswap.js
core/zoe/contracts/coveredCall.js
core/zoe/contracts/helpers/offerRules.js
core/zoe/contracts/publicAuction.js
core/zoe/contracts/publicSwap.js
core/zoe/contracts/simpleExchange.js
core/zoe/zoe/zoe.js
core/zoe/zoe/zoeUtils.js
test/swingsetTests/zoe/vat-bob.js
test/unitTests/core/test-seat.js
test/unitTests/core/zoe/contracts/helpers/test-offerRules.js
test/unitTests/core/zoe/contracts/test-coveredCall.js
test/unitTests/core/zoe/test-zoeUtils.js

* The `id` in the extents of `seatMint` had mistakenly been renamed to `offerHandle`, even though the id/handle was meant to be an unique identifier for the value of the payment, not anything in particular to do with an offer.
* Add more comments and better organization to Zoe
* remove excess info from the invite extents.

More simplifications and clean up

---

core/zoe/contracts/autoswap.js
test/unitTests/core/zoe/contracts/test-autoswap.js

The code for calculating the autoswap fee was wrongly adding it to the pool. This version follows the formula in the Uniswap constant product invariant paper.

Autoswap Fee Calc

---

core/mint.chainmail
core/mint.js
core/unitOps.chainmail
test/swingsetTests/splitPayments/vat-alice.js
test/unitTests/core/test-mint.js

I was going through issues and realized #174 was a quick fix. I was especially motivated because there's an embarrassing typo in which replacing "AssetDesc" with "Unit" created "Unitss".  
This PR fixes the typos and the Unit/Unit Ops Description.

Fix typos and UnitOps description

---

package-lock.json
package.json

This prepares for a monorepo, where we want packages/ERTP to provide
`0.1.12` (not `0.1.13-dev.0`), to be compatible with e.g.
packages/cosmic-swingset (which will declare a dependency upon `~0.1.12`,
which is not satisfied by `0.1.13-dev.0`).

package.json: roll back .dev0 version

---

more/sharing/sharedMap.js
more/sharing/sharing.js
test/swingsetTests/gallery/bootstrap.js
test/swingsetTests/gallery/test-gallery.js
test/swingsetTests/gallery/vat-alice.js
test/swingsetTests/gallery/vat-bob.js
test/swingsetTests/sharingService/bootstrap.js
test/swingsetTests/sharingService/test-sharing.js
test/swingsetTests/sharingService/vat-alice.js
test/swingsetTests/sharingService/vat-bob.js
test/swingsetTests/zoe/test-zoe.js
test/unitTests/more/sharing/test-sharing.js

This was supposed to follow the renaming of handoff service, but got lost somehow.

rename corkboard to sharedMap

---

core/zoe/zoe/zoe.js
test/swingsetTests/zoe/test-zoe.js

This is needed to be compatible with future bundle formats.
It apparently looks like this code can be simplified or eliminated, but it exists to explicitly declare what moduleFormats are accepted by Zoe.  When more formats are added or support for old ones is removed, this will be an important safeguard.

fix(zoe): have install accept a moduleFormat argument
