Agoric/ERTP

- README.md
> document ERTP by way of Miller @ SFBW presentation

- demo/gallery/bootstrap.js
- demo/gallery/vat-alice.js
- demo/gallery/vat-bob.js
- demo/gallery/vat-host.js
- more/pixels/gallery.js
- test/demo/test-gallery-demo.js
- test/more/pixels/test-gallery.js
This adds a function that allows a user to sell a pixel to the gallery.
> add the ability to sell a pixel to the gallery

- more/pixels/gallery.js
- test/demo/test-gallery-demo.js
Make the initial pixels at least a little more colourful.  More can be done.
> more/pixels/gallery: fake out randomness

- more/pixels/gallery.js
Our randomization code sometimes doesn't return a valid color (missing a digit). This tests for that case and adds a digit if needed, and also errors if that still doesn't fix it. Eventually I'd like to change the actual algorithm but I won't understand the bit operations fully without diving in further.
Closes #23
> Our randomization code sometimes doesn't return a valid color 

- demo/gallery/bootstrap.js
- demo/gallery/vat-alice.js
- more/pixels/gallery.js
- test/demo/test-gallery-demo.js
The gallery userFacet now has a function called `buyFromGallery` which allows the user to pass in a pixelAmount that specifies their desired pixels. If someone has previously sold those pixels to the gallery, the gallery prices the pixels, and instantiates an escrow smart contract where the user is able to pay the price to receive the pixels.
> Implement buyFromGallery function with tests

- demo/gallery/vat-alice.js
- more/pixels/gallery.js
- test/more/pixels/test-gallery.js
> rename functions to something shorter. 

- demo/gallery/bootstrap.js
- demo/gallery/vat-alice.js
- demo/gallery/vat-bob.js
- demo/gallery/vat-handoff.js
- more/pixels/gallery.js
- test/demo/test-gallery-demo.js
- test/more/pixels/test-gallery.js
A test to demonstrate Alice selling pixels to Bob through the handoff service.
> Test handoff

- scripts/npm-audit-fix.sh
This adds our usual script for the agoricbot to do `npm audit` and create a PR if there is anything to change.
> Add npm-audit-fix script

- core/issuers.js
The new realms-shim rejects things that look like ``, so this line needs to be modified.
> issuers: remove false-positive HTML comment

- core/issuers.js
- core/mintController.js
- demo/gallery/vat-bob.js
- more/pixels/gallery.js
- more/pixels/pixelMintController.js
* Renames the parameters and methods in `mintController.js` and `pixelMintController.js` for clarity
* Makes required subsequent changes to `issuers.js`
* Adds `getName()` functions to purses and payments
* removes `isPurse` parameter from `takePayment` because that was used in the context of hardcoded useRights which were taken out. 
Closes #39
> Clean up mintController and issuers.js

- CONTRIBUTING.md
- NEWS.md
Adds a log of changes per release. @Chris-Hibbert do these descriptions look right to you?
> Add NEWS.md

- package-lock.json
- package.json
* "ses": "^0.6.0"
* "@agoric/swingset-vat": "0.0.20"
* "eslint": "^6.3.0",
* "eslint-config-prettier": "^6.2.0",
> Update eslint, eslint-config-prettier, swingset-vat, SES

- core/contractHost.js
- core/coveredCall.js
- package-lock.json
- package.json
- test/swingsetTests/contractHost/bootstrap.js
- test/swingsetTests/contractHost/vat-alice.js
- test/swingsetTests/contractHost/vat-fred.js
Update to:
```
@agoric/evaluate        1.3.2   1.3.2   2.1.1  @agoric/ertp
@agoric/marshal         0.1.0   0.1.1   0.1.1  @agoric/ertp
@agoric/swingset-vat   0.0.22  0.0.22  0.0.26  @agoric/ertp
@babel/core             7.6.0   7.6.2   7.6.2  @agoric/ertp
eslint                  6.4.0   6.5.1   6.5.1  @agoric/ertp
ses                     0.6.1   0.6.3   0.6.3  @agoric/ertp
```
`E.resolve` no longer works, so `E.resolve` was replaced with `Promise.resolve`
> Update to latest, E.resolve -> Promise.resolve

- core/contractHost.chainmail
https://github.com/Agoric/Documentation/pull/12/files/a00db5b6602cf0283446fa3386d6c11c4d422981#r330826825
@davidBruant
> add description of invitePayments

- core/contractHost.js
Please see this change to make the contractHost compatible with the new `ag-solo upload-contract` bundling mechanism.
> feat(contractHost): support new moduleFormat bundling

- core/zoe/contracts/publicSwap.js
Without trying to reuse the same framework as the second price auction, we can simplify a bit
> Refactor public swap

- core/zoe/contracts/publicAuction.js
- core/zoe/contracts/publicSwap.js
Refactor the public second price auction
> Refactor the public second price auction

- core/zoe/contracts/publicSwap.js
- core/zoe/zoe/zoe.js
Instead of using ===, use extentOps
> Fix isMatchingOfferDesc

- CHAINMAIL.md
Quick writeup on context and usage of chainmail.
> Chainmail doc

- core/zoe/contracts/autoswap/methods/addLiquidity.js
- core/zoe/contracts/autoswap/methods/getPrice.js
- core/zoe/contracts/coveredCall.js
- core/zoe/contracts/publicAuction.js
- core/zoe/contracts/publicSwap.js
- core/zoe/contracts/simpleExchange.js
- core/zoe/zoe/state.js
- core/zoe/zoe/zoe.js
- core/zoe/zoe/zoeUtils.js
* `getExtentOps` -> `getExtentOpsArray` in Zoe governing contract facet
* move helper functions out of `addOrder` in `simpleExchange`
* rename `Order` to `Offer` internally in `simpleExchange`
> Slight changes to Simple Exchange

- core/zoe/docs/publicAuction.md
- core/zoe/docs/publicSwap.md
- core/zoe/zoe/state.js
- core/zoe/zoe/zoe.js
- test/swingsetTests/zoe/bootstrap.js
- test/swingsetTests/zoe/test-zoe.js
- test/swingsetTests/zoe/vat-alice.js
- test/swingsetTests/zoe/vat-bob.js
- test/swingsetTests/zoe/vat-carol.js
- test/swingsetTests/zoe/vat-dave.js
- test/unitTests/core/zoe/contracts/test-automaticRefund.js
- test/unitTests/core/zoe/contracts/test-coveredCall.js
- test/unitTests/core/zoe/contracts/test-publicAuction.js
- test/unitTests/core/zoe/contracts/test-publicSwap.js
- test/unitTests/core/zoe/contracts/test-simpleExchange.js
This PR adds SwingSet tests for all of the Zoe contracts apart from autoswap.
> Add SwingSet Tests for Zoe Contracts

- core/zoe/contracts/publicSwap.js
- core/zoe/contracts/simpleExchange.js
Add handling of cancelled offers to PublicSwap and SimpleExchange
> Add handling of cancelled offers to PublicSwap and SimpleExchange

- core/zoe/contractUtils.js
- core/zoe/contracts/automaticRefund.js
- core/zoe/docs/zoe.md
- core/zoe/zoe.chainmail
- core/zoe/zoe/zoe.js
- test/unitTests/core/zoe/contracts/test-automaticRefund.js
- test/unitTests/core/zoe/contracts/test-coveredCall.js
Talk about the Zoe Service rather than the "user facet" and leave out mentions of "governing" contracts
> Talk about the Zoe Service rather than the "user facet"

- core/coveredCall.js
- core/zoe/zoe/zoe.js
- test/swingsetTests/contractHost/bootstrap.js
- tools/manualTimer.js
Make Zoe and the coveredCall use a timer with an interface that matches the timerService, and update their tests.
> Update timer used by contracts to match timerService

- core/zoe/zoe/zoe.js
- test/unitTests/core/zoe/contracts/test-autoswap.js
* remove `await` from `await makeState`
* fix autoswap test to actually test the assays
> Address Zoe PR comments

- core/zoe/docs/offerSafety.md
- core/zoe/docs/publicAuction.md
- core/zoe/docs/publicSwap.md
- core/zoe/docs/zoe.md
- core/zoe/zoe.chainmail
- core/zoe/zoe/areRightsConserved.js
- core/zoe/zoe/isOfferSafe.js
- test/unitTests/core/zoe/test-areRightsConserved.js
- test/unitTests/core/zoe/test-isOfferSafe.js
Added doc on offer safety gotchas. Fixed documentation to always refer to offer safety without hyphen.
> Read and corrected comments in `isOfferSafe.js` and `areRightsConserved.js`.

- core/config/configs.md
- core/config/seatConfig.js
Explains why and how we use generators to express trait combination.
> explain traits and remove useless returns

- core/zoe/contracts/myFirstDapp.js
- test/unitTests/core/zoe/contracts/test-myFirstDapp.js
Adds a smart contract that has a similar interface to autoswap but which is very very simple.
> Add "myFirstDapp"

- package-lock.json
- package.json
same goal as #232, to let the most recent versions of all the swingset-related packages declare compatibility with each other
> upgrade to latest swingset-0.3.0 and bundle-source-1.0.4

- package-lock.json
- package.json
- test/swingsetTests/zoe/test-zoe.js
- test/swingsetTests/zoe/vat-alice.js
- test/unitTests/core/zoe/contracts/test-automaticRefund.js
- test/unitTests/core/zoe/contracts/test-publicAuction.js
- test/unitTests/core/zoe/contracts/test-publicSwap.js
- test/unitTests/core/zoe/contracts/test-simpleExchange.js
- test/unitTests/core/zoe/test-areRightsConserved.js
- test/unitTests/core/zoe/test-zoeUtils.js
- test/unitTests/more/pixels/types/test-pixel-list.js
and rewrap some tests to appease the new heuristic
> Upgrade prettier
